---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: 查看適用於您的Trident配置的設定選項。 
---
= 儲存配置選項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
查看適用於您的Trident配置的設定選項。



== 全域配置選項

這些配置選項適用於所有Trident配置，無論使用何種儲存平台。

[cols="3*"]
|===
| 選項 | 描述 | 例子 


| `version`  a| 
設定檔版本號
 a| 
`1`



| `storageDriverName`  a| 
儲存驅動程式名稱
 a| 
`ontap-nas`， `ontap-san` ， `ontap-nas-economy` ，
`ontap-nas-flexgroup` ， `solidfire-san`



| `storagePrefix`  a| 
卷名稱的可選前綴。預設: `netappdvp_` 。
 a| 
`staging_`



| `limitVolumeSize`  a| 
對容量大小有可選限制。預設值：""（不強制執行）
 a| 
`10g`

|===

TIP: 請勿使用 `storagePrefix`（包括預設值）適用於 Element 後端。預設情況下， `solidfire-san`驅動程式將忽略此設置，並且不使用前綴。  NetApp建議使用特定的租用戶 ID 進行 Docker 磁碟區映射，或使用屬性數據，該屬性資料填入了 Docker 版本、驅動程式資訊和來自 Docker 的原始名稱（如果可能使用了任何名稱修改）。

可以使用預設選項，避免在建立的每個磁碟區上都指定這些選項。這 `size`此選項適用於所有控制器類型。有關如何設定預設磁碟區大小的範例，請參閱ONTAP配置部分。

[cols="3*"]
|===
| 選項 | 描述 | 例子 


| `size`  a| 
新磁碟區的可選預設大小。預設: `1G`
 a| 
`10G`

|===


== ONTAP 配置

除了上述全域配置值之外，使用ONTAP時，還可以使用下列頂級選項。

[cols="3*"]
|===
| 選項 | 描述 | 例子 


| `managementLIF`  a| 
ONTAP管理 LIF 的 IP 位址。您可以指定一個完全限定網域名稱（FQDN）。
 a| 
`10.0.0.1`



| `dataLIF`  a| 
LIF協定的IP位址。

* ONTAP NAS 驅動程式*： NetApp建議指定 `dataLIF`。如果未提供， Trident將從 SVM 取得 dataLIF。您可以指定一個完全限定網域名稱 (FQDN) 用於 NFS 掛載操作，從而建立輪詢 DNS 以在多個 dataLIF 之間進行負載平衡。

* ONTAP SAN 驅動程式*：請勿指定 iSCSI 或 FC。Trident的使用link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP選擇性 LUN 地圖"^]發現建立多路徑會話所需的 iSCSI 或 FC LIF。如果出現以下情況，則會產生警告： `dataLIF`已明確定義。
 a| 
`10.0.0.2`



| `svm`  a| 
要使用的儲存虛擬機器（如果管理 LIF 是叢集 LIF，則此項目為必填項）
 a| 
`svm_nfs`



| `username`  a| 
連接到儲存裝置的使用者名
 a| 
`vsadmin`



| `password`  a| 
連接儲存裝置的密碼
 a| 
`secret`



| `aggregate`  a| 
用於配置的聚合（可選；如果設置，則必須指派給 SVM）。對於 `ontap-nas-flexgroup`驅動程序，此選項將被忽略。指派給 SVM 的所有聚合都用於配置FlexGroup磁碟區。
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
可選，如果使用率超過此百分比，則配置失敗
 a| 
`75%`



| `nfsMountOptions`  a| 
對 NFS 掛載選項進行精細控制；預設值為“-o nfsvers=3”。  *僅限以下情況： `ontap-nas`和 `ontap-nas-economy`司機*。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["請在此處查看 NFS 主機設定資訊"^] 。
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Trident建立和管理每個節點 `igroups`作為 `netappdvp`。

此值不能更改或省略。

*僅限以下情況： `ontap-san`司機*。
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
最大可請求容量。
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
每個FlexVol 的最大 qtree 數量必須在 [50, 300] 範圍內，預設值為 200。

*對於 `ontap-nas-economy`驅動程序，此選項允許自訂每個FlexVol* 的最大 qtree 數量。
 a| 
`300`



 a| 
`sanType`
| *支持 `ontap-san`僅限司機。 *用於選擇 `iscsi`對於 iSCSI， `nvme`適用於 NVMe/TCP 或 `fcp`用於光纖通道 (FC) 上的 SCSI。 | `iscsi`如果為空 


| `limitVolumePoolSize` | *支持 `ontap-san-economy`和 `ontap-san-economy`僅限司機。 *限制ONTAP ontap-nas-economy 和 ontap-SAN-economy 驅動程式中的FlexVol大小。  a| 
`300g`

|===
系統提供了預設選項，避免在建立的每個磁碟區上都進行指定：

[cols="1,3,2"]
|===
| 選項 | 描述 | 例子 


| `spaceReserve`  a| 
空間預約模式； `none` （精簡配置）或 `volume`（厚的）
 a| 
`none`



| `snapshotPolicy`  a| 
要使用的快照策略，預設值為 `none`
 a| 
`none`



| `snapshotReserve`  a| 
快照預留百分比，預設值為空字串，表示接受ONTAP預設值。
 a| 
`10`



| `splitOnClone`  a| 
創建時將克隆體與其父級分離，預設為 `false`
 a| 
`false`



| `encryption`  a| 
在新磁碟區啟用NetApp磁碟區加密 (NVE)；預設為啟用 `false`。若要使用此選項，必須在叢集上取得 NVE 許可並啟用 NVE。

如果後端啟用了 NAE，則在Trident中配置的任何磁碟區都會啟用 NAE。

更多信息，請參閱：link:../trident-reco/security-reco.html["Trident如何與 NVE 和 NAE 協同工作"] 。
 a| 
真的



| `unixPermissions`  a| 
NAS 選項，用於已配置的 NFS 卷，預設值為 `777`
 a| 
`777`



| `snapshotDir`  a| 
NAS 存取選項 `.snapshot`目錄。
 a| 
NFSv4 為“true”，NFSv3 為“false”。



| `exportPolicy`  a| 
NFS匯出策略要使用的NAS選項，預設值為 `default`
 a| 
`default`



| `securityStyle`  a| 
NAS 選項，用於存取已設定的 NFS 磁碟區。

NFS 支持 `mixed`和 `unix`安全措施。預設值為 `unix`。
 a| 
`unix`



| `fileSystemType`  a| 
SAN 選項用於選擇檔案系統類型，預設為 `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
要使用的分層策略，預設值為 `none`。
 a| 
`none`

|===


=== 縮放選項

這 `ontap-nas`和 `ontap-san`驅動程式為每個 Docker 磁碟區建立一個ONTAP FlexVol 。  ONTAP每個叢集節點最多支援 1000 個 FlexVol，叢集最多可支援 12,000 個FlexVol磁碟區。如果您的 Docker 磁碟區需求符合此限制，則 `ontap-nas`由於 FlexVols 提供了 Docker 磁碟區粒度快照和克隆等附加功能，因此驅動程式是首選的 NAS 解決方案。

如果您需要的 Docker 磁碟區數量超過了FlexVol 的限制，請選擇 `ontap-nas-economy`或者 `ontap-san-economy`司機。

這 `ontap-nas-economy`驅動程式在自動管理的FlexVol磁碟區中建立作為ONTAP Qtree 的 Docker 磁碟區。 Qtree 提供了更大的可擴展性，每個叢集節點最多可達 100,000 個節點，每個叢集最多可達 2,400,000 個節點，但代價是犧牲了一些功能。這 `ontap-nas-economy`驅動程式不支援 Docker 磁碟區粒度快照或克隆。


NOTE: 這 `ontap-nas-economy`Docker Swarm 目前不支援該驅動程序，因為 Docker Swarm 無法協調跨多個節點的磁碟區建立。

這 `ontap-san-economy`驅動程式在自動管理的FlexVol磁碟區的共用池中建立 Docker 磁碟區作為ONTAP LUN。這樣一來，每個FlexVol就不限於一個 LUN，並且為 SAN 工作負載提供了更好的可擴充性。根據儲存陣列的不同， ONTAP每個叢集最多支援 16384 個 LUN。由於這些磁碟區底層是 LUN，因此此驅動程式支援 Docker 磁碟區粒度快照和複製。

選擇 `ontap-nas-flexgroup`驅動程式可提高單一磁碟區的平行處理能力，該磁碟區可成長到 PB 級，包含數十億個檔案。  FlexGroups 的一些理想用例包括 AI/ML/DL、大數據和分析、軟體建置、串流媒體、檔案儲存庫等等。  Trident在配置FlexGroup磁碟區時會使用指派給 SVM 的所有聚合。  Trident中的FlexGroup支援還需考慮以下幾點：

* 需要ONTAP版本 9.2 或更高版本。
* 截至撰寫本文時，FlexGroups 僅支援 NFS v3。
* 建議為 SVM 啟用 64 位元 NFSv3 識別碼。
* 建議的最小FlexGroup成員/磁碟區大小為 100 GiB。
* FlexGroup卷不支援克隆。


有關 FlexGroup 以及適合 FlexGroup 的工作負載的信息，請參閱以下內容： https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup卷最佳實務與實作指南"^] 。

為了在同一環境中獲得進階功能和大規模部署，您可以執行多個 Docker Volume Plugin 實例，其中一個使用 `ontap-nas`以及另一個使用 `ontap-nas-economy`。



=== 為Trident訂製ONTAP角色

您可以建立一個具有最低權限的ONTAP叢集角色，這樣您就不必使用ONTAP管理員角色在Trident中執行操作。在Trident後端設定中包含使用者名稱時， Trident將使用您建立的ONTAP叢集角色來執行操作。

請參閱link:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Trident自訂角色產生器"]有關建立Trident自訂角色的詳細資訊。

[role="tabbed-block"]
====
.使用ONTAP CLI
--
. 使用以下命令建立新角色：
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. 為Trident用戶建立使用者名稱：
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. 將角色映射到使用者：
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.使用系統管理員
--
在ONTAP系統管理員中執行下列步驟：

. *建立自訂角色*：
+
.. 若要在叢集層級建立自訂角色，請選擇「叢集 > 設定」。
+
（或）若要在 SVM 層級建立自訂角色，請選擇「儲存」>「儲存虛擬機器」> `required SVM` > 設定 > 使用者和角色*。

.. 選擇“使用者和角色”旁邊的箭頭圖示（*->*）。
.. 在“角色”下選擇“+添加”。
.. 定義角色規則，然後點選「儲存」。


. 將角色對應到Trident使用者： + 在「使用者和角色」頁面上執行下列步驟：
+
.. 在「使用者」下方選擇「新增」圖示 *+*。
.. 選擇所需的使用者名，然後在「角色」下拉式選單中選擇角色。
.. 點選“儲存”。




--
====
更多資訊請參閱以下頁面：

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["用於管理ONTAP的自訂角色"^]或者link:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["定義自訂角色"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["與角色和使用者協作"^]




=== ONTAP設定檔範例

.<code>ontap-nas</code>驅動程式的NFS範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.<code>ontap-nas-flexgroup</code>驅動程式的NFS範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.<code>ontap-nas-economy</code> 驅動程式的 NFS 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.<code>ontap-san</code> 驅動程式的 iSCSI 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.<code>ontap-san-economy</code> 驅動程式的 NFS 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.<code>ontap-san</code> 驅動程式的 NVMe/TCP 範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.<code>ontap-san</code>驅動程式的基於FC的SCSI範例
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Element軟體配置

除了全域設定值之外，在使用 Element 軟體（NetApp HCI/ SolidFire）時，還可以使用這些選項。

[cols="3*"]
|===
| 選項 | 描述 | 例子 


| `Endpoint`  a| 
https://<登入>:<密碼>@<mvip>/json-rpc/<元素版本>
 a| 
https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
iSCSI IP 位址和連接埠
 a| 
10.0.0.7:3260



| `TenantName`  a| 
要使用的 SolidFireF 租用戶（如果未找到則建立）
 a| 
`docker`



| `InitiatorIFace`  a| 
將 iSCSI 流量限制在非預設介面時，請指定介面。
 a| 
`default`



| `Types`  a| 
QoS規範
 a| 
請參閱下面的範例



| `LegacyNamePrefix`  a| 
升級版Trident安裝的前綴。如果您使用的是 1.3.2 之前的Trident版本，並且使用現有磁碟區執行升級，則需要設定此值才能存取透過磁碟區名稱方法對應的舊磁碟區。
 a| 
`netappdvp-`

|===
這 `solidfire-san`驅動程式不支援 Docker Swarm。



=== 範例元素軟體設定檔

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----