---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: 每個儲存驅動程式都有一組不同的選項，您可以在建立磁碟區時指定這些選項以自訂結果。請參閱下方適用於您配置的儲存系統的選項。 
---
= 驅動程式特定音量選項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個儲存驅動程式都有一組不同的選項，您可以在建立磁碟區時指定這些選項以自訂結果。請參閱下方適用於您配置的儲存系統的選項。

在建立磁碟區操作期間使用這些選項非常簡單。提供選項和值 `-o`CLI 操作期間的運算子。這些值會覆寫 JSON 設定檔中的任何等效值。



== ONTAP容量選項

NFS、iSCSI 和 FC 的磁碟區建立選項包括以下幾種：

[cols="2*"]
|===
| 選項 | 描述 


| `size`  a| 
卷大小預設為 1 GiB。



| `spaceReserve`  a| 
容量配置方式可以是精簡配置或厚配置，預設為精簡配置。有效值為 `none`（精簡配置）和 `volume`（厚配置）。



| `snapshotPolicy`  a| 
這將把快照策略設定為所需值。預設值為 `none`這意味著不會自動為該磁碟區建立快照。除非儲存管理員修改，否則所有ONTAP系統上都存在一個名為「default」的策略，該策略會建立並保留 6 個每小時快照、2 個每日快照和 2 個每週快照。可以透過瀏覽來還原快照中保存的資料。 `.snapshot`卷中任意目錄中的目錄。



| `snapshotReserve`  a| 
這將把快照預留量設定為所需的百分比。預設值為空，這表示如果您選擇了 snapshotPolicy， ONTAP將選擇 snapshotReserve（通常為 5%）；如果 snapshotPolicy 為 none，則 ONTAP 將選擇 snapshotReserve（通常為 5%）。您可以在設定檔中為所有ONTAP後端設定預設 snapshotReserve 值，並且可以將其用作除 ontap-nas-economy 之外的所有ONTAP後端的磁碟區建立選項。



| `splitOnClone`  a| 
克隆卷時，這將導致ONTAP立即將克隆卷與其父卷分離。預設值為 `false`。有些克隆卷的用例最好在創建後立即將克隆卷與其父卷分離，因為不太可能有機會提高儲存效率。例如，克隆一個空資料庫可以節省大量時間，但節省的儲存空間卻很少，因此最好立即拆分克隆。



| `encryption`  a| 
在新磁碟區啟用NetApp磁碟區加密 (NVE)；預設為 `false`。若要使用此選項，必須在叢集上取得 NVE 許可並啟用 NVE。

如果後端啟用了 NAE，則在Trident中配置的任何磁碟區都會啟用 NAE。

更多信息，請參閱：link:../trident-reco/security-reco.html["Trident如何與 NVE 和 NAE 協同工作"] 。



| `tieringPolicy`  a| 
設定磁碟區要使用的分層策略。這決定了當資料變成不活動狀態（冷資料）時，是否將其遷移到雲層。

|===
以下附加選項僅適用於 NFS：

[cols="2*"]
|===
| 選項 | 描述 


| `unixPermissions`  a| 
這控製卷本身的權限集。預設情況下，權限將設定為 ``---rwxr-xr-x`或以數字表示法表示為 0755，且 `root`將成為所有者。文字格式或數字格式均可。



| `snapshotDir`  a| 
將其設定為 `true`將使 `.snapshot`用戶端存取該磁碟區時可見的目錄。預設值為 `false`這意味著可見性 `.snapshot`目錄預設為禁用狀態。某些鏡像，例如官方的 MySQL 鏡像，在以下情況下無法如預期運作： `.snapshot`目錄可見。



| `exportPolicy`  a| 
設定該磁碟區要使用的匯出策略。預設值為 `default`。



| `securityStyle`  a| 
設定用於存取磁碟區的安全樣式。預設值為 `unix`。有效值為 `unix`和 `mixed`。

|===
以下附加選項僅適用於 iSCSI：

[cols="2*"]
|===
| 選項 | 描述 


| `fileSystemType` | 設定用於格式化 iSCSI 磁碟區的檔案系統。預設值為 `ext4`。有效值為 `ext3`， `ext4` ， 和 `xfs`。 


| `spaceAllocation` | 將其設定為 `false`將關閉 LUN 的空間分配功能。預設值為 `true`這表示當磁碟區空間不足且磁碟區中的 LUN 無法接受寫入時， ONTAP會通知主機。此選項還允許ONTAP在主機刪除資料時自動回收空間。 
|===


=== 範例

請看以下範例：

* 建立一個 10 GiB 卷：
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* 建立一個帶有快照的 100 GiB 磁碟區：
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* 建立一個啟用了 setUID 位元的磁碟區：
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


最小磁碟區大小為 20 MiB。

如果未指定快照保留，且快照策略為 `none`Trident使用 0% 的快照儲備。

* 建立一個沒有快照策略和快照保留的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* 建立一個沒有快照策略且自訂快照保留比例為 10% 的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* 建立一個具有快照策略和 10% 自訂快照保留空間的磁碟區：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* 建立具有快照策略的捲，並接受 ONTAP 的預設快照保留（通常為 5%）：
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element 軟體音量選項

Element 軟體選項會顯示與磁碟區相關的大小和服務品質 (QoS) 策略。建立磁碟區時，使用下列方式指定與其關聯的 QoS 策略： `-o type=service_level`命名法。

使用 Element 驅動程式定義 QoS 服務等級的第一步是建立至少一個類型，並在設定檔中指定與名稱關聯的最小、最大和突發 IOPS。

Element軟體的其他磁碟區建立選項包括以下幾種：

[cols="2*"]
|===
| 選項 | 描述 


| `size`  a| 
卷的大小，預設為 1 GiB 或配置條目...“defaults”：{“size”：“5G”}。



| `blocksize`  a| 
可使用 512 或 4096，預設值為 512 或設定項 DefaultBlockSize。

|===


=== 例子

請參閱以下包含 QoS 定義的範例設定檔：

[source, json]
----
{
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----
在上述配置中，我們有三個策略定義：青銅、白銀和黃金。這些名稱是隨意起的。

* 創建 10 GiB 黃金卷：
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 創建 100 GiB 青銅卷：
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

