---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: '透過將Trident與Amazon FSx for NetApp ONTAP結合使用，您可以確保在 Amazon Elastic Kubernetes Service (EKS) 中執行的 Kubernetes 叢集可以設定由ONTAP支援的區塊和檔案持久性磁碟區。' 
---
= 安裝Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident簡化了 Kubernetes 中Amazon FSx for NetApp ONTAP儲存管理，讓您的開發人員和管理員能夠專注於應用程式部署。

您可以使用下列方法之一安裝Trident ：

* 舵
* EKS 附加元件


如果要使用快照功能，請安裝 CSI 快照控制器外掛程式。請參閱link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["為CSI磁碟區啟用快照功能"^]了解更多。



== 透過 Helm 安裝Trident。

[role="tabbed-block"]
====
.Pod 身份
--
. 新增Trident Helm 倉庫：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 請依照以下範例安裝Trident ：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
您可以使用 `helm list`查看安裝詳細資訊的命令，例如名稱、命名空間、圖表、狀態、應用程式版本和修訂號。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.服務帳戶協會（IRSA）
--
. 新增Trident Helm 倉庫：
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 設定*雲端提供者*和*雲端身分*的值：
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
您可以使用 `helm list`查看安裝詳細資訊的命令，例如名稱、命名空間、圖表、狀態、應用程式版本和修訂號。

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
如果您打算使用 iSCSI，請確保您的用戶端電腦上已啟用 iSCSI。如果您使用的是 AL2023 工作節點作業系統，可以透過在 Helm 安裝中新增節點準備參數來自動安裝 iSCSI 用戶端：

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== 透過 EKS 外掛程式安裝Trident

Trident EKS 外掛程式包含最新的安全性修補程式和錯誤修復，並經過 AWS 驗證，可與 Amazon EKS 搭配使用。  EKS 外掛程式可讓您持續確保您的 Amazon EKS 叢集安全穩定，並減少安裝、設定和更新外掛程式所需的工作量。



=== 先決條件

在為 AWS EKS 設定Trident外掛程式之前，請確保您已具備以下條件：

* 附加訂閱的 Amazon EKS 叢集帳戶
* AWS 對 AWS Marketplace 的權限：
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* AMI 類型：Amazon Linux 2 (AL2_x86_64) 或 Amazon Linux 2 Arm (AL2_ARM_64)
* 節點類型：AMD 或ARM
* 現有的Amazon FSx for NetApp ONTAP檔案系統




=== 為 AWS 啟用Trident插件

[role="tabbed-block"]
====
.管理控制台
--
. 開啟 Amazon EKS 主控台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左側導覽窗格中，選擇「集群」。
. 選擇要為其配置NetApp Trident CSI 外掛程式的叢集名稱。
. 選擇“附加元件”，然後選擇“取得更多附加元件”。
. 請依照以下步驟選擇外掛：
+
.. 向下捲動至「AWS Marketplace 附加元件」部分，然後在搜尋框中輸入「Trident」。
.. 選取「Trident by NetApp」方塊右上角的複選框。
.. 選擇“下一步”。


. 在「配置所選外掛」設定頁面上，執行以下操作：
+

NOTE: *如果您使用 Pod Identity 關聯，請跳過這些步驟。 *

+
.. 請選擇您要使用的*版本*。
.. 如果您使用IRSA身份驗證，請確保設定可選配置設定中提供的配置值：
+
*** 請選擇您要使用的*版本*。
*** 依照*外掛程式設定方案*進行操作，並將*配置值*部分中的*configurationValues*參數設定為您在上一個步驟建立的角色 ARN（值應採用下列格式）：




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
如果選擇「覆蓋」作為衝突解決方法，則現有外掛程式的一個或多個設定可能會被 Amazon EKS 外掛程式設定覆蓋。如果您不啟用此選項，並且與您現有的設定有衝突，則操作將會失敗。您可以使用產生的錯誤訊息來排查衝突問題。在選擇此選項之前，請確保 Amazon EKS 外掛程式不會管理您需要自行管理的設定。

. 選擇“下一步”。
. 在「審核和新增」頁面上，選擇「建立」。
+
插件安裝完成後，您將看到已安裝的插件。



--
.AWS CLI
--
*1.創建 `add-on.json`文件*：

*對於 Pod 標識，請使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*對於IRSA認證，請使用以下格式*：

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: 代替 `<role ARN>`使用上一步創建的角色的 ARN。

*2.安裝Trident EKS 外掛程式。 *

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
以下範例指令安裝Trident EKS 外掛：

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== 更新Trident EKS 外掛

[role="tabbed-block"]
====
.管理控制台
--
. 開啟 Amazon EKS 主控台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左側導覽窗格中，選擇「集群」。
. 選擇要更新NetApp Trident CSI 外掛程式的叢集名稱。
. 選擇“附加元件”標籤。
. 選擇“ NetApp Trident ”，然後選擇“編輯”。
. 在「配置NetApp Trident 」頁面上，執行以下操作：
+
.. 請選擇您要使用的*版本*。
.. 展開“可選配置設定”，並根據需要進行修改。
.. 選擇“儲存變更”。




--
.AWS CLI
--
以下範例更新 EKS 外掛：

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* 請檢查您的 FSxN Trident CSI 外掛程式的目前版本。代替 `my-cluster`使用您的叢集名稱。
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*範例輸出：*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* 將插件更新到上一步輸出中「UPDATE AVAILABLE」下傳回的版本。
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


如果你移除 `--force`如果選項和任何 Amazon EKS 外掛程式設定與您現有的設定衝突，則更新 Amazon EKS 外掛程式將失敗；您將收到錯誤訊息，以協助您解決衝突。在指定此選項之前，請確保 Amazon EKS 外掛程式不會管理您需要管理的設置，因為此選項會覆寫這些設定。有關此設定的其他選項的更多信息，請參閱link:https://eksctl.io/usage/addons/["外掛"]。有關 Amazon EKS Kubernetes 欄位管理的更多信息，請參閱link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Kubernetes 欄位管理"]。

--
====


=== 解除安裝/移除Trident EKS 插件

您可以透過兩種方式移除 Amazon EKS 外掛：

* *保留叢集上的附加軟體* – 此選項移除 Amazon EKS 對所有設定的管理。它還取消了 Amazon EKS 通知您更新以及在您啟動更新後自動更新 Amazon EKS 外掛程式的功能。但是，它可以保留叢集上的附加軟體。此選項使外掛程式成為自管理安裝，而不是 Amazon EKS 外掛程式。選擇此選項，插件不會出現停機時間。保留 `--preserve`命令中的選項用於保留插件。
* *從叢集中完全移除附加軟體* – NetApp建議，僅當叢集中沒有任何資源依賴 Amazon EKS 附加元件時，才會從叢集中移除該附加元件。移除 `--preserve`選項 `delete`移除插件的命令。



NOTE: 如果外掛程式關聯了 IAM 帳戶，則不會刪除該 IAM 帳戶。

[role="tabbed-block"]
====
.管理控制台
--
. 開啟 Amazon EKS 主控台 https://console.aws.amazon.com/eks/home#/clusters[]。
. 在左側導覽窗格中，選擇「集群」。
. 選擇要從中移除NetApp Trident CSI 外掛程式的叢集名稱。
. 選擇“附加元件”選項卡，然後選擇“ NetApp Trident ”。
. 選擇*刪除*。
. 在「移除 netapp_trident-operator 確認」對話方塊中，執行下列操作：
+
.. 如果您希望 Amazon EKS 停止管理外掛程式的設置，請選擇「在叢集上保留」。如果您希望在叢集上保留附加軟體，以便您可以自行管理附加軟體的所有設置，請執行此操作。
.. 輸入 *netapp_trident-operator*。
.. 選擇*刪除*。




--
.AWS CLI
--
代替 `my-cluster`輸入叢集名稱，然後執行以下命令。

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
以下指令卸載Trident EKS 外掛程式：

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====