= 
:allow-uri-read: 


. （可選）如果您只需要選擇應用程式中的某些資源進行恢復，請新增篩選條件，以包含或排除帶有特定標籤的資源：
+

NOTE: Trident Protect 會自動選擇一些資源，因為它們與您選擇的資源有關聯。例如，如果您選擇持久性磁碟區宣告資源且它有一個關聯的 pod， Trident Protect 也會還原關聯的 pod。

+
** *resourceFilter.resourceSelectionCriteria*：（篩選時必備）使用 `Include`或者 `Exclude`包含或排除 resourceMatchers 中定義的資源。新增以下 resourceMatchers 參數以定義要包含或排除的資源：
+
*** *resourceFilter.resourceMatchers*：resourceMatcher 物件陣列。如果在該數組中定義多個元素，則它們之間按 OR 運算匹配，每個元素內的字段（組、種類、版本）之間按 AND 運算匹配。
+
**** *resourceMatchers[].group*: (_可選_) 要篩選的資源群組。
**** *resourceMatchers[].kind*: (_可選_) 要篩選的資源類型。
**** *resourceMatchers[].version*: (_可選_) 要篩選的資源版本。
**** *resourceMatchers[].names*: (_可選_) 要過濾的資源的 Kubernetes 元資料.name 欄位中的名稱。
**** *resourceMatchers[].namespaces*: (_可選_) 要篩選的資源的 Kubernetes 元資料.name 欄位中的命名空間。
**** *resourceMatchers[].labelSelectors*: (_可選_) 資源的 Kubernetes 元資料.name 欄位中的標籤選擇器字串，如在下列位置定義： https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["Kubernetes 文檔"^] 。例如： `"trident.netapp.io/os=linux"` 。
+
例如：

+
[source, yaml]
----
spec:
  resourceFilter:
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
----







