---
sidebar: sidebar 
permalink: trident-get-started/k8s-netapp.html 
keywords: kubernetes, netapp storage, ontap, cloud volumes ontap, santricity, element software, netapp hci, anf, azure netapp files, cloud volumes service for google cloud, gcp, aws, amazon fsx 
summary: NetApp的儲存產品組合與 Kubernetes 叢集的許多不同面向集成，提供進階資料管理功能，從而增強 Kubernetes 部署的功能、能力、效能和可用性。 
---
= Kubernetes 與NetApp產品集成
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp的儲存產品組合與 Kubernetes 叢集的許多不同面向集成，提供進階資料管理功能，從而增強 Kubernetes 部署的功能、能力、效能和可用性。



== Trident

https://docs.netapp.com/us-en/trident/["Trident"^]使企業能夠更輕鬆地管理、保護和遷移在公有雲內部和跨公有雲以及本地環境中運行的、資料豐富的容器化工作負載（這些工作負載運行在 Kubernetes 上）。 Trident利用NetApp久經考驗且功能強大的儲存產品組合中的Trident ，在公有雲和本地環境中提供持久容器儲存。它還提供了一套豐富的、高級的、應用感知的資料管理功能，例如快照、備份和復原、活動日誌和主動克隆，用於 Kubernetes 工作負載的資料保護、災難/資料復原、資料稽核和遷移用例。



== ONTAP

ONTAP是NetApp 的多協定統一儲存作業系統，可為任何應用程式提供進階資料管理功能。  ONTAP系統具有全快閃、混合或全 HDD 配置，並提供多種不同的部署模型，包括工程硬體（FAS和AFF）、白盒（ONTAP Select）和僅限雲端（ Cloud Cloud Volumes ONTAP）。


NOTE: Trident支援上述所有ONTAP部署模型。



== Cloud Volumes ONTAP

http://cloud.netapp.com/ontap-cloud?utm_source=GitHub&utm_campaign=Trident["Cloud Volumes ONTAP"^]是一款純軟體儲存設備，可在雲端運行ONTAP資料管理軟體。您可以使用Cloud Volumes ONTAP進行生產工作負載、災難復原、DevOps、檔案共用和資料庫管理。它透過提供儲存效率、高可用性、資料複製、資料分層和應用程式一致性，將企業儲存擴展到雲端。



== Amazon FSx for NetApp ONTAP

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^]是一項完全託管的 AWS 服務，可讓您啟動並執行由NetApp ONTAP儲存作業系統支援的檔案系統。  FSx for ONTAP讓您能夠利用您熟悉的NetApp功能、效能和管理能力，同時享受在 AWS 上儲存資料的簡單性、敏捷性、安全性和可擴充性。  FSx for ONTAP支援ONTAP檔案系統的許多功能和管理 API。



== Element軟體

https://www.netapp.com/data-management/element-software/["元素"^]透過確保效能並實現簡化和精簡的儲存佈局，使儲存管理員能夠整合工作負載。  Element 結合了 API，可實現儲存管理各個方面的自動化，使儲存管理員能夠事半功倍。



== NetApp HCI

https://www.netapp.com/virtual-desktop-infrastructure/netapp-hci/["NetApp HCI"^]透過自動化日常任務，簡化資料中心的管理和擴展，使基礎設施管理員能夠專注於更重要的功能。

NetApp HCI完全受Trident支援。  Trident可以直接針對底層NetApp HCI儲存平台，為容器化應用程式設定和管理儲存設備。



== Azure NetApp Files

https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^]是由NetApp支援的企業級 Azure 檔案共用服務。您可以在 Azure 中原生運行要求最高的基於文件的工作負載，並獲得您期望從NetApp獲得的高效能和豐富的資料管理功能。



== Google Cloud NetApp Volumes

https://cloud.netapp.com/cloud-volumes-service-for-gcp?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^]是一個雲端原生檔案服務，它透過 NFS 提供 NAS 卷，並具有全快閃效能。這項服務使任何工作負載（包括傳統應用程式）都能在 GCP 雲端中運作。它提供完全託管的服務，可提供持續的高效能、即時複製、資料保護以及對 Google Compute Engine (GCE) 執行個體的安全存取。
