---
sidebar: sidebar 
permalink: trident-concepts/provisioning.html 
keywords: provisioning, Trident 
summary: Trident的配置流程分為兩個主要階段。第一階段將儲存類別與一組適當的後端儲存池關聯起來，這是在進行設定之前必須進行的準備工作。第二階段包含磁碟區的建立本身，需要從與待建立磁碟區的儲存類別關聯的儲存池中選擇儲存池。 
---
= 供應
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident的配置流程分為兩個主要階段。第一階段將儲存類別與一組適當的後端儲存池關聯起來，這是在進行設定之前必須進行的準備工作。第二階段包含磁碟區的建立本身，需要從與待建立磁碟區的儲存類別關聯的儲存池中選擇儲存池。



== 儲存類別關聯

將後端儲存池與儲存類別關聯起來，取決於儲存類別的請求屬性及其 `storagePools`， `additionalStoragePools` ， 和 `excludeStoragePools`列表。建立儲存類別時， Trident會將其每個後端提供的屬性和池與儲存類別請求的屬性和池進行比較。如果儲存池的屬性和名稱與所有要求的屬性和池名稱相符， Trident會將該儲存池新增至該儲存類別的適用儲存池集合中。此外， Trident還新增了清單中列出的所有儲存池。 `additionalStoragePools`即使它們的屬性不滿足儲存類別的所有或任何請求屬性，也要將其新增至該集合。你應該使用 `excludeStoragePools`列出要覆蓋和移除儲存類別所使用的儲存池。每次新增的後端時， Trident都會執行類似的流程，檢查其儲存池是否符合現有儲存類別的要求，並刪除任何被標記為排除的儲存池。



== 銷售創造

Trident然後利用儲存類別和儲存池之間的關聯來確定在哪裡配置磁碟區。建立磁碟區時， Trident首先取得該磁碟區儲存類別的儲存池集合，如果您為該磁碟區指定了協議， Trident會刪除那些無法提供所要求協定的儲存池（例如， NetApp HCI/ SolidFire後端無法提供基於檔案的磁碟區，而ONTAP NAS 後端無法提供基於區塊的磁碟區）。 Trident會隨機化所得集合的順序，以方便磁碟區的均勻分佈，然後遍歷該集合，依序嘗試在每個儲存池上配置磁碟區。如果一次成功，則傳回成功結果，並將流程中遇到的任何失敗記錄下來。  Trident僅在無法為要求的儲存類別和協定配置所有可用的儲存池時才會傳回失敗。
