---
sidebar: sidebar 
permalink: trident-protect/trident-protect-restore-settings.html 
keywords: trident, protect, restore, data, backup 
summary: 您可以使用註解、命名空間設定和儲存選項自訂Trident保護復原作業。 
---
= 使用進階Trident保護恢復設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用進階設定（例如註解、命名空間設定和儲存選項）自訂復原操作，以滿足您的特定要求。



== 復原和故障轉移操作期間的命名空間註釋和標籤

在復原和故障轉移操作期間，目標命名空間中的標籤和註釋將與來源命名空間中的標籤和註釋相符。來源命名空間中不存在的目標命名空間中的標籤或註釋將被添加，並且任何已存在的標籤或註釋都將被覆蓋以匹配來源命名空間中的值。僅存在於目標命名空間中的標籤或註解保持不變。


NOTE: 如果您使用 Red Hat OpenShift，請務必注意命名空間註解在 OpenShift 環境中的重要角色。命名空間註解可確保復原的 pod 遵守 OpenShift 安全性情境約束 (SCC) 定義的適當權限和安全性配置，並且可以存取磁碟區而不會出現權限問題。欲了解更多信息，請參閱 https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/authentication_and_authorization/managing-pod-security-policies["OpenShift 安全上下文約束文檔"^]。

您可以透過設定 Kubernetes 環境變數來防止目標命名空間中的特定註解被覆蓋。 `RESTORE_SKIP_NAMESPACE_ANNOTATIONS`在執行復原或故障轉移操作之前。例如：

[source, console]
----
helm upgrade trident-protect --set restoreSkipNamespaceAnnotations=<annotation_key_to_skip_1>,<annotation_key_to_skip_2> --reuse-values
----

NOTE: 執行復原或故障轉移操作時，任何命名空間註解和標籤都將生效。 `restoreSkipNamespaceAnnotations` 和 `restoreSkipNamespaceLabels` 不參與恢復或故障轉移操作。確保在初始 Helm 安裝期間配置這些設定。欲了解更多信息，請參閱 link:../trident-protect/trident-protect-customize-installation.html#configure-autoSupport-and-namespace-filtering-options["配置AutoSupport和命名空間過濾選項"]。

如果您使用 Helm 安裝了來源應用程序， `--create-namespace`國旗，給予特殊待遇 `name`標籤鍵。在復原或故障轉移過程中， Trident Protect 會將此標籤複製到目標命名空間，但如果來源命名空間的值與來源命名空間的值匹配，則會將值更新為目標命名空間的值。如果此值與來源命名空間不匹配，則會將其複製到目標命名空間，而不做任何變更。



=== 例子

以下範例展示了來源命名空間和目標命名空間，每個命名空間都有不同的註解和標籤。您可以查看操作前後目標命名空間的狀態，以及目標命名空間中的註解和標籤是如何組合或覆蓋的。



==== 在恢復或故障轉移操作之前

下表說明了復原或故障轉移操作之前範例來源命名空間和目標命名空間的狀態：

[cols="1,2a,2a"]
|===
| 命名空間 | 註解 | 標籤 


| 命名空間 ns-1（來源）  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"

 a| 
* 環境=生產
* 合規性=HIPAA
* 名稱=ns-1




| 命名空間 ns-2（目標）  a| 
* annotation.one/key: "true"
* annotation.three/key: "false"

 a| 
* 角色=資料庫


|===


==== 恢復操作後

下表說明了復原或故障轉移作業後範例目標命名空間的狀態。有些按鍵已被添加，有些按鍵已被覆蓋，並且 `name`標籤已更新，以符合目標命名空間：

[cols="1,2a,2a"]
|===
| 命名空間 | 註解 | 標籤 


| 命名空間 ns-2（目標）  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
* annotation.three/key: "false"

 a| 
* 名稱=ns-2
* 合規性=HIPAA
* 環境=生產
* 角色=資料庫


|===


== 支援的字段

本節介紹可用於恢復操作的其他欄位。



=== 儲存類別映射

這 `spec.storageClassMapping`屬性定義了從來源應用程式中存在的儲存類別到目標叢集上新儲存類別的對應。您可以在具有不同儲存類別的叢集之間移轉應用程式時或變更 BackupRestore 作業的儲存後端時使用此功能。

*例：*

[source, yaml]
----
storageClassMapping:
  - destination: "destinationStorageClass1"
    source: "sourceStorageClass1"
  - destination: "destinationStorageClass2"
    source: "sourceStorageClass2"
----


== 支持的註釋

本節列出了系統中用於配置各種行為的支援註解。如果使用者沒有明確設定註釋，系統將使用預設值。

[cols="1,1,3,1"]
|===
| 註解 | 類型 | 描述 | 預設值 


| protect.trident.netapp.io/data-mover-timeout-sec | 細繩 | 資料移動器操作允許停止的最長時間（以秒為單位）。 | “300” 


| protect.trident.netapp.io/kopia-content-cache-size-limit-mb | 細繩 | Kopia 內容快取的最大大小限制（以兆位元組為單位）。 | “1000” 
|===