---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'Trident Protect 使管理員能夠產生包含對NetApp支援有用的信息的捆綁包，包括有關所管理的叢集和應用程式的日誌、指標和拓撲資訊。如果您已連接到互聯網，則可以使用自訂資源 (CR) 檔案將支援包上傳至NetApp支援網站 (NSS)。' 
---
= 產生Trident Protect 支援包
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect 使管理員能夠產生包含對NetApp支援有用的信息的捆綁包，包括有關所管理的叢集和應用程式的日誌、指標和拓撲資訊。如果您已連接到互聯網，則可以使用自訂資源 (CR) 檔案將支援包上傳至NetApp支援網站 (NSS)。

[role="tabbed-block"]
====
.使用 CR 建立支援包
--
.步驟
. 建立自訂資源 (CR) 檔案並將其命名為（例如， `trident-protect-support-bundle.yaml` ）。
. 配置以下屬性：
+
** *metadata.name*: (_必填_) 此自訂資源的名稱；請為您的環境選擇一個唯一且有意義的名稱。
** *spec.triggerType*: (_Required_) 確定支援包是立即產生還是按計劃產生。計劃的資料包產生時間為世界協調時凌晨 12 點。可能的值：
+
*** 已安排
*** 手動的


** *spec.uploadEnabled*: (_可選_) 控制產生支援包後是否應將其上傳至NetApp支援網站。如果未指定，則預設為 `false`。可能的值：
+
*** 真的
*** false（預設值）


** *spec.dataWindowStart*: (_可選_) RFC 3339 格式的日期字串，指定支援包中包含的資料視窗應開始的日期和時間。如果未指定，則預設為 24 小時前。您最早可以指定的日期範圍是 7 天前。
+
YAML 範例：

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. 填寫完後 `trident-protect-support-bundle.yaml`將檔案的值正確後，套用 CR：
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml -n trident-protect
----


--
.使用 CLI 建立支援包
--
.步驟
. 建立支援包，將括號中的值替換為您環境中的資訊。這 `trigger-type`決定捆綁包是立即建立還是由計劃安排決定創建時間，並且可以是 `Manual`或者 `Scheduled`。預設是 `Manual`。
+
例如：

+
[source, console]
----
tridentctl-protect create autosupportbundle <my-bundle-name> --trigger-type <trigger-type> -n trident-protect
----


--
====


== 監視和檢索支援包

使用任一方法建立支援包後，您可以監視其產生進度並將其檢索到本機系統。

.步驟
. 等待 `status.generationState`到達 `Completed`狀態。您可以使用以下命令監控產生進度：
+
[source, console]
----
kubectl get autosupportbundle trident-protect-support-bundle -n trident-protect
----
. 將支援包檢索到您的本機系統。從已完成的AutoSupport套件中取得複製指令：
+
[source, console]
----
kubectl describe autosupportbundle trident-protect-support-bundle -n trident-protect
----
+
找到 `kubectl cp`從輸出中讀取命令並運行它，將目標參數替換為您首選的本機目錄。


